- files/sensu-gem/sysvinit/sensu-api
- files/sensu-gem/sysvinit/sensu-client
- files/sensu-gem/sysvinit/sensu-server
- files/sensu-gem/sysvinit/sensu-service-init
This changes the stop priority for systems where chkconfig is in use, ensuring
that Sensu services stop before other services they may depend on or monitor.
Per https://github.com/sensu/sensu-build/pull/94:
> sensu processes should terminate earlier than other processes.
> The case of setting for automatic start in process monitoring,
> it will start the process that has become stopped by shutdown process.
Closes https://github.com/sensu/sensu-build/pull/94
Closes https://github.com/sensu/sensu-build/issues/182
> [sysvinit] change chkconfig stop order

- package-scripts/sensu/postinst
As described in #34 we need logic to let us continue using sysv scripts. The
intent is to make it less painful to update existing systems.
Closes #38
> [postinst] continue using sysv on systemd systems when already present

- files/sensu-gem/bin/sensu-service
In da0aebb3bbd936f32170e58b7efc5d6ea7daf173 we reassigned the CONFIG_DIR variable to indicate the path for Sensu's root configuration directory (e.g. /etc/sensu) and added a variable CONFD_DIR to indicate the path for glob-loading Sensu config files. It seems we did not update the `options` and `validate_options` strings accordingly. This change fixes that oversight.
> use CONFD_DIR in sensu-service binstub options

- files/sensu-gem/sysvinit/sensu-service-init
Currently the sysv init script will exit if it fails to kill the PID specified by the pidfile, causing restart action to fail when we have a stale pidfile.
This change tests to see if the pid specified by the pidfile is running, exiting normally if it is not, allowing the restart action to succeed despite a stale pidfile.
Closes https://github.com/sensu/sensu/issues/1295
> [sysvinit] return 0 if pid from file isn't running

- config/projects/sensu.rb
With this change I am able to build rpms without providing GPG credentials
> update condition guarding rpm signing using GPG_PASSPHRASE env var

- .kitchen.yml
box offered by bento project isn't usable on macs. seems to be a problem with
vbox paravirtualization that causes VM to enter an invalid state. We built our
own box with `--paravirtprovider none` which works for our needs right now.
> update kitchen config to use our own build of centos-5.11 box

- site-cookbooks/omnibus_sensu/recipes/freebsd_portsnap.rb
The portsnap cron option was the wrong choice as it can offset the operation by up to 3600 seconds. This is to stagger the fetching of the ports tree across multiple servers when done on a scheduled basis.
The `--interactive` option should work. I've updated the recipe to place portsnap options before the `fetch extract` command in hopes that this will solve the problem when using the `kitchen-ec2` driver.
> Use portsnap --interactive

- .gitignore
- .kitchen.cloud.yml
- Gemfile
- site-cookbooks/omnibus_sensu/attributes/default.rb
- site-cookbooks/omnibus_sensu/metadata.rb
- site-cookbooks/omnibus_sensu/recipes/default.rb
These changes are intended to make our build process work IN DA CLOUD ☁.
In order to use the included `.kitchen.cloud.yml`, I've set the following environment variables :
```
export AWS_REGION=us-west-2
export AWS_DEFAULT_REGION=us-west-2
export AWS_SSH_KEY_ID=cameron-hw
export AWS_SSH_KEY_PATH=~/.ssh/cameron-hw-aws.pem
export KITCHEN_LOCAL_YAML=~/github/sensu-omnibus/.kitchen.cloud.yml
```
> Add config yaml and update cookbook to support kitchen-ec2 driver

- Gemfile
Update bundle to use `sensu` branch of sensu/omnibus instead of `master`, as `master` has been rolled back to follow upstream.
> use sensu branch of sensu/omnibus fork

- site-cookbooks/omnibus_sensu/recipes/default.rb
The git_config provider does not work independently of the install methods,
which do not currently support freebsd, so we're moving them back into a
conditional that skips them on freebsd systems.
This reverts commit 0d9d6c61ee54bf249f941e9a108f8d3a2892d16c.
> [chef] Revert "apply git_config resources on all platforms"

- build.sh
When the build is tagged more than once, build.sh currently detects only the
first tag. This makes it likely that the system will build artifacts for a build
number that already exists. By failing the build under these conditions we hope
to avoid wasting cycles on building the wrong thing.
> [travis] fail the build when multiple tags detected on same commit

- .travis.yml
Let's give higher priority to more recent Linux platforms by running them first,
and add Windows 2012r2 to our matrix.
Windows builds take almost 2hrs to complete, so we're counting on the charity of
our friends at Travis CI to have made a behind-the-scenes change for us.
> [travis] reprioritize job matrix, add windows-2012-r2

- .kitchen.yml
- README.md
Our FreeBSD 10 i386 build is currently failing. This is due to the `pkg` command segfaulting when we try to install sudo and the latest CA Root certificates. After some research I have discovered that this is due to the latest `pkg` command not supporting FreeBSD 10.1 which is what our build AMI includes.
It seems that FreeBSD stopped publishing i386 cloud images for AWS after FreeBSD 10.1 was released. As a result we will need to build our own AMI (based on a release >= 10.3 and < 11) to support FreeBSD 10 i386 builds.
This PR removes FreeBSD 10 i386 from our build pipeline (for now).
> Drop test-kitchen support for freebsd-10-i386

- config/software/sensu-gem.rb
We've encountered errors upgrading Sensu deb packages on systems where
sensu-enterprise is installed:
```
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/etc/sensu/conf.d/.keep', which is also in
package sensu-enterprise 2.2.0-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/etc/sensu/plugins/.keep', which is also in
package sensu-enterprise 2.2.0-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/var/log/sensu/.keep', which is also in
package sensu-enterprise 2.2.0-1
dpkg: warning: unable to delete old directory '/etc/sensu/handlers': Directory
not empty
```
We really only need these .keep files for some subset of packgers which will
omit empty …
> [sensu-gem] only touch .keep files for non-linux platforms

- config/templates/package-scripts/postrm.erb
- config/templates/package-scripts/prerm.erb
FreeBSD builds are failing because we forgot to account for that platform in our
erb templates. Oops!
> [package-scripts] add freebsd to platform_family conditions

- config/software/sensu-gem.rb
fixes `Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/sensu/conf.d/.keep` during omnibus build
> [sensu-gem] only add extra_package_file for .keep files on non-linux platforms

- config/software/sensu-gem.rb
Attempting to build packages without the `.keep` files again. I'd like to determine if this will fix our Linux packages and which platforms' packagers do not support empty directories.
> Remove keepfiles, add parent dirs

- files/sensu-gem/sensu-client-windows.xml
In interactive testing I've had no luck using `<arguments>` (plural), so this
implementation uses `<argument>` (singular) tags, and adds -c flag for behavior
consistent with Linux installations.
Assumes existence of C:\opt\sensu\conf.d, a directory which isn't currently created by the MSI.
> [sensu_gem] update sensu-client-windows.xml with known-working copy

- config/software/sensu-gem.rb
Until we can figure out how to control files outside of install_dir on Windows, let's create a conf.d directory in c:/opt/sensu for configuration to be stored.
> Create C:/opt/sensu/conf.d on Windows

- config/software/rubysl-readline-gem.rb
- config/software/sensu-gem.rb
The `rb-readline` gem does not seem to work on FreeBSD. I manually installed the `rubysl-readline` gem as an alternative and it appears to be functioning correctly.
> Use rubysl-readline on FreeBSD instead of rb-readline

- config/software/winsw.rb
Version 2.0.0 of winsw contains a regression which broke backward compatibility with `<arguments>` tags. This change updates our use of winsw to the 2.0.1 version, which fixes this regression.
> [winsw] update to version 2.0.1

- build.sh
Relies on --sort behavior present in Git 2.0 and later.
Also updated script syntax to pass [shellcheck](http://www.shellcheck.net/) linter.
Closes #108
> [travis] refactor build.sh to handle commits with multiple tags

- config/templates/package-scripts/postinst.erb
- config/templates/package-scripts/postrm.erb
- config/templates/package-scripts/preinst.erb
- config/templates/package-scripts/prerm.erb
Due to the nature of RPM scriptlet ordering, anyone upgrading from one omnibus-built package to another will result in `/opt/sensu` vanishing. These changes should prevent the scripts from running on anything but an RPM uninstall action.
See https://fedoraproject.org/wiki/Packaging:Scriptlets#Scriptlet_Ordering for more information.
> Only run prerm/postrm scripts on RPM uninstall action

- config/templates/sensu-gem/sysvinit/sensu-service.erb
The service wrapper that the sysvinit script calls is run as the `sensu` user which does not have the correct permissions to create the pid directory (`/var/run/sensu`). This PR adds functionality to the sysvinit script to ensure the pid dir exists as root.
Fixes https://github.com/sensu/sensu/issues/1543
> Ensure pid dir exists in sysvinit script

- build.sh
We previously tried to make our build script support multiple tags in #113, which had to be revered due to Travis providing git 1.8, too old for the approach used there.
This approach reverse sorts the tags found by git, on the assumption that the newest tag by date will also be the tag we want to build.
Closes #108
> Another attempt at updating build.sh to handle commits with multiple tags

- config/templates/package-scripts/config.erb
- config/templates/package-scripts/postinst.erb
- config/templates/package-scripts/prerm.erb
AIX seems to run the `postinst` script prior to finishing the extraction / ownership correction of package files. The `config` script is run afterward so I've copied the `postinst` logic into the new `config` script.
I've also added a few changes to protect against commands, which should be allowed to fail, that may cause the scripts to fail.
> Add config script for AIX

- config/templates/package-scripts/postinst.erb
As of 0.27.1-1 I am seeing errors on fresh install and upgrade, i.e. the following on Ubuntu:
```
/var/lib/dpkg/info/sensu.postinst: 104: /var/lib/dpkg/info/sensu.postinst: Syntax error: "}" unexpected
```
and on Centos:
```
/var/tmp/rpm-tmp.nA2uvr: line 104: syntax error near unexpected token `}'
warning: %post(sensu-1:0.27.1-1.el7.x86_64) scriptlet failed, exit status 2
Non-fatal POSTIN scriptlet failure in rpm package 1:sensu-0.27.1-1.el7.x86_64
Verifying  : 1:sensu-0.27.1-1.el7.x86_64                                                                                                                                   1/1
```
This change should ensure that the `create_system_services` function is not empty and also a no-op on platforms other than AIX.
> [package-scripts/postinst] ensure create_system_services() is not empty

- config/software/eventmachine.rb
In https://github.com/sensu/sensu/pull/1562 Sensu's direct dependencies updated EM from 1.2.1 to 1.2.2 but the definition here was not updated. As a result, we published packages which contain EM 1.2.1 from this definition, and EM 1.2.2 without proper OpenSSL support on some platforms (see #124).
This update to 1.2.2 should remove the duplication in the package, and ensure the loaded version of EM has working SSL.
Closes #124
> [software/eventmachine] update to 1.2.2

- resources/sensu/msi/source.wxs.erb
This is an attempt to resolve an issue where multiple copies of Sensu can be simultaneously installed on Windows.
> Revert to sensu-build wix upgrade logic

- config/software/eventmachine.rb
These compile options are present in https://github.com/sensu/sensu-build/blob/master/recipes/sensu.rake but didn't make it into the omnibus software config.
> [software/eventmachine] add --with-ssl* compile options for windows

- resources/sensu/msi/source.wxs.erb
After merging #128 I encountered the following during MSI build:
```
C:\Users\Administrator\AppData\Local\Temp\sensu20170221-2928-4typwk\source.wxs(34) : error LGHT0094 : Unresolved reference to symbol 'WixAction:InstallExecuteSequence/RemoveExistingProducts' in section 'Product:*'.
```
The changes in this PR seem to clear up this error, and the resulting package installs successfully, with a singular version of Sensu present in "Programs and Features"
> [resources/msi] define RemoveExistingProducts in source.wxs.erb

- .kitchen.yml
This change should ensure that EBS volumes are deleted on termination. From examining the block device mapping of running Windows and Linux build instances, I believe this /dev/sda1 device name is suitable for both platforms.
> [test-kitchen] configure driver to delete ebs volumes on termination

- Berksfile.lock
- config/projects/sensu.rb
- site-cookbooks/omnibus_sensu/recipes/default.rb
* Avoid using custom methods and helpers that are out of scope when conditionally setting value for `signing_passphrase`
* Write GPG passphrase to file instead of injecting into ENV as this will inevitably be leaked into CI logs when compilation fails.
> Fix RPM signing

- config/software/openssl.rb
Contains fixes for the following CVEs:
https://www.openssl.org/news/vulnerabilities.html#2017-3731
https://www.openssl.org/news/vulnerabilities.html#2017-3732
https://www.openssl.org/news/vulnerabilities.html#2016-7055
> [software/openssl] update to 1.0.2k

- config/software/sensu-gem.rb
In the more recent versions of macOS, certain system directories are protected from being written to (including `/usr/bin`). It appears that it is recommended to use `/usr/local/bin` as an alternative.
> Place sensu-install in /usr/local/bin on macOS

- config/software/openssl.rb
I goofed and tagged 0.28.1-1 on master instead of the release branch, which means this update is already shipped in our 0.28.1-1 packages.
> Cherrypick openssl 1.0.2k update to release/0.28 branch

- config/software/sensu-gem.rb
Adds support for globally disabling the library's deprecated filter methods.
> Update sensu-plugin version to 1.4.5

- config/templates/sensu-gem/sysvinit/sensu-service.erb
The sysvinit script should exit with a status code of 0 when trying to stop and already stopped service.
Fixes #120
> LSB compatibility fix

- resources/sensu/pkg/license.html.erb
Unfortunately, the HTML-formatted license did not get rendered as I had expected it to. This PR removes all of the HTML from the MIT license we include with our Mac packages.
> Remove HTML from Mac license

- config/software/winsw.rb
This update includes a fix to improve termination of child processes.
See https://github.com/kohsuke/winsw/issues/95 and https://github.com/kohsuke/winsw/pull/186
> Update winsw to 2.0.2

- config/software/sensu-gem.rb
- helpers.rb
As noted by #163, the systemd service files that are installed by the Linux packages should not have the execute bit set on them. This PR should fix #163.
> Systemd service files should not be executable

- config/patches/openssl/openssl-1.0.2k-no-bang.patch
- config/software/openssl.rb
This PR updates our OpenSSL recipe to the latest from the omnibus-software repository (with our Windows changes re-applied). The no-bang patch is necessary for our builds to succeed on Solaris 10.
> Update to latest OpenSSL recipe from omnibus-software

- config/software/rubygems.rb
This will enable the installation of rubygems from tarball on Solaris 10 only. It fixes an OpenSSL verification issue during the Solaris 10 build process.
> Install rubygems from source on Solaris 10

- config/software/ruby.rb
I mistakingly added the SHA256 checksum for the .tar.bz2 package of Ruby 2.4.1. This PR corrects the mistake.
> Use correct SHA256 checksum for Ruby 2.4.1 .tar.gz

- config/templates/sensu-gem/sysvinit/sensu-service.erb
- files/sensu-gem/bin/sensu-install
- files/sensu-gem/sensu-install.bat
It would be ideal if we could pass the version of Ruby via the omnibus definition into templates to ensure that these versions are updated automatically, but for now this will do...
> Update GEM_PATH to 2.4.0

- config/software/ruby.rb
- config/software/sensu-gem.rb
This PR moves the CFLAGS needed for the Sensu gem to install on Solaris 10 to Ruby where it will be used when installing any ruby gem.
It also adds some new CFLAGS and CPPFLAGS to the ruby definition that are necessary to make builds succeed on Solaris 11.
> Solaris 10/11 CFLAGS/CPPFLAGS fixes & relocation

- .kitchen.yml
- site-cookbooks/omnibus_sensu/recipes/default.rb
Trying to address persistent build failures on Windows related to Taking Too Darn Long
* Update windows kitchen config to use AMI generated from [sensu-omnibus-packer](https://github.com/sensu/sensu-omnibus-packer/pull/2)
* Configure timeout on omnibus_build resource, depends on https://github.com/sensu/omnibus-cookbook/pull/2 (not yet contributed back upstream)
> Omnibus build timeout

- config/software/winsw.rb
In testing 0.29.0-2 MSI packages are missing sensu-client.exe. I believe this is because the source file name was not updated in the winsw software component configuration. This change should help 🌮
> [winsw] fix source filename in copy directive

- site-cookbooks/omnibus_sensu/recipes/default.rb
Per https://travis-ci.org/sensu/sensu-omnibus/jobs/218204007 and others:
```
bundler: command not found: omnibus
Install missing gem executables with `bundle install`
```
> [chef] ensure bundle is installed before populating cache

- site-cookbooks/omnibus_sensu/recipes/default.rb
When running as `omnibus` user, the build fails on Debian and Centos:
```
There was an error while trying to write to `/root/.bundle/cache/git`. It is
likely that you need to grant write permissions for that path.
```
> [chef] run cache population as root user

- files/sensu-gem/sensu-client-windows.xml
> Use WinSW for logging on Windows (STDOUT/STDERR), rotate logs every 100 MB

- config/projects/sensu.rb
Functionally identical but doesn't include Qt (among other needless things in the giant redhat-lsb package)
> constrain dependencies to those strictly needed

- config/software/sensu-gem.rb
sensu-plugin 2.0.1 loosens dependency on json gem from < 2.0.0 to < 3.0.0. See https://github.com/sensu-plugins/sensu-plugin/pull/173
> Update sensu-plugin 2.0.0 to 2.0.1

- config/projects/sensu.rb
Just requires a documentation change elsewhere, as these are not, strictly speaking, 'sensu' dependencies.
> Remove all redhat-lsb / initscript deps

- config/projects/sensu.rb
- config/software/sensu-gem.rb
Should fix #166 for Linux packages only. The packagers on other platforms will likely need some work to specify Omnibus-specified "config_files" as configuration files. This needs to be tested.
> Add logrotate & defaults files as config files on linux

- .gitignore
- .kitchen.yml
- Berksfile
- Gemfile
- Rakefile
- config/projects/sensu.rb
- config/software/shebang-cleanup.rb
- site-cookbooks/omnibus_sensu/recipes/default.rb
- Simplifies testing of changes on Windows outside of Travis - run `rake archive` to generate an archive that can be picked up by the chef cookbook, meaning less commit/tag pollution and no having to go to Github anyway (this being purely optional).
- Properly orders dependencies in the project definition; fixes what looks like a bug in the shebang-cleanup definition.
I was able to build successfully locally with this; Travis is running now!
> Unblock build failures on Windows

- helpers.rb
/etc/systemd should only be used for machine-specific overrides. (https://www.freedesktop.org/software/systemd/man/systemd.unit.html)
> Package provided systemd files should not go to /etc

- platform-docs/AIX.md
As we now build on AIX 7.2 (6.1 has been retired on IBM PDP) the platform docs for AIX need to be updated.
> Update AIX platform docs for AIX 7.2

- config/templates/sensu-gem/systemd/sensu-service.erb
Per https://sensucommunity.slack.com/archives/C68LV5M9U/p1501783154845983 it seems we are not using systemd's facilities for ensuring our services start after the network is available. This change should address that oversight.
> Prevent systemd services from starting before network is online

- .kitchen.yml
- build.sh
test-kitchen will use value of PPROJECT_REVISION env var to determine
which revision of this repository to check for building.
> build.sh now passes git tag as value of PROJECT_REVISION

- helpers.rb
After merging https://github.com/sensu/sensu-omnibus/pull/220 we have realized that the path used for systemd services does not exist on debian platforms. This PR stores the service files in `/lib/systemd/system` instead which will work across both debian & centos platforms as centos symlinks `/lib` to `/usr/lib`.
> debian systemd services are stored in /lib/systemd, not /usr/lib/systemd

- config/projects/sensu.rb
- config/software/sensu-gem.rb
- config/software/winsw-net2.rb
- config/software/winsw-net4.rb
- resources/sensu/msi/source.wxs.erb
MSI now determines whether .NET Framework version ==2.0 or  >= 4.0 is available and copy the corresponding winsw executable in `\opt\sensu\bin` to `sensu-client.exe`.
~Installer now raises an error if no suitable .NET Framework is available.~ In keeping with prior installer behavior, no error is raised when .NET Framework is not available.
❤️  to @amdprophet for slogging through this with me!
Closes #234
> Detect .NET version and install corresponding winsw variant

- config/templates/sensu-gem/smf/sensu-service.erb
- platform-docs/AIX.md
This was missed when we created the `sensu-service` binstub. I've tested this and it's now functional.
> Adjust Solaris SMF to properly use sensu-service binstub

- site-cookbooks/omnibus_sensu/recipes/default.rb
This fixes an issue where centos-5, centos-5-i386, and centos-6-i386 were not able to git clone this repository.
> Use git bundled with omnibus-toolchain instead of system git

- .kitchen.yml
CentOS 7.5 updates the binutils package to version 2.27 which adds support for the `--compress-debug-sections=zlib` LDFLAG. When Ruby is built on CentOS 7.5 it is adding the LDFLAG to rbconfig which breaks the installation of some Sensu plugins on CentOS 7.4 or earlier.
> Pin CentOS 7 AMI

- config/templates/sensu-gem/systemd/sensu-service.erb
I think there have been some confusion in this pr: https://github.com/sensu/sensu-omnibus/pull/229
I first noticed some strange issues on our servers, where the sensu-client was sometimes loaded, sometime not, without any reasonable explanations.
I then realized that when it was not loaded, the `network-online.target` systemd unit was not reached too.
So the bug appeared on servers where sensu-client was the *only* service needing `network-online.target`.
The systemd documentation is pretty clear: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/#cutthecraphowdoimakesurethatmyservicestartsafterthenetworkisreallyonline
So we *must* use `Wants=network-online.target` (which is obvious when you realize that network-online must be pulled in), and to avoid chicken/eggs issues, …
> Fix systemd unit

- config/software/libtool.rb
Inside libtool, libltdl also tries to run config.guess which fails
on platforms like aarch64.  This patch adds it to the list of folders
which are updated with newer config.guess to get aarch64 support.
We can also provide CI resources for Sensu if you'd like to run aarch64
builds on our OpenStack cloud
Signed-off-by: Mohammed Naser <mnaser@vexxhost.com>
> [aarch64] Add updated config.guess to libltdl

- files/sensu-gem/bin/sensu-install
This change is needed to allow sensu-install to run in the default shell in Solaris (and likely AIX too).
> Improve compatibility for sensu-install on non-bash platforms

- config/patches/libffi/libffi-3.2.1-makefiles-sparc.patch
- config/patches/ruby/ruby-no-m32-cflag.patch
- config/patches/ruby/ruby-remove-headc.patch
- config/software/libffi.rb
- config/software/ruby.rb
A few things of note:
* `head -c` is not a valid flag on Solaris 10; use `dd count=` instead
* Had to remove the `-m32` flag that the ruby configure script adds
* The `-O3` CFLAG makes ruby builds unhappy with the error `There are only 32 single precision f registers`
> Solaris 10 sparc fixes

- plan.tf
Adds plan.tf which provisions a VPC and related resources required for launching test-kitchen instances in this project. 
This implementation uses the existing sensu-omnibus-artifacts S3 bucket as a remote backend to store infrastructure state, so we should be able to make changes in the future without starting over.
> Add terraform plan for building required infrastructure
