sensu/sensu-omnibus

package-scripts/sensu/postrm
=> Remove user/group in Linux postrm

resources/sensu/rpm/rpmmacros.erb, resources/sensu/rpm/signing.erb, resources/sensu/rpm/spec.erb
=> Hardcode epoch to 1 for rpms

.kitchen.yml, Gemfile, config/software/config_guess.rb, config/software/eventmachine.rb, config/software/libstdc++.rb, config/software/sensu-gem.rb, config/templates/sensu-gem/rc.d/sensu-service.erb, files/sensu-gem/bin/sensu-service, helpers.rb, package-scripts/sensu/postinst, package-scripts/sensu/postrm, site-cookbooks/omnibus_sensu/recipes/default.rb, site-cookbooks/omnibus_sensu/recipes/freebsd_portsnap.rb
Adds FreeBSD pkgng build support. Closes #25.
=> FreeBSD support

config/software/libffi.rb, config/software/rb-readline-gem.rb, config/software/sensu-gem.rb
=> Add readline support

config/software/sensu-gem.rb
sensu-plugin 1.4.3 [contains a regression][1] which is now fixed in 1.4.4.
[1]: https://github.com/sensu-plugins/sensu-plugin/issues/160
=> Update sensu-plugin for bugfix

README.md
=> update readme to describe automation pipeline and env vars

config/templates/package-scripts/postrm.erb, config/templates/package-scripts/prerm.erb
We have previously addressed bugs in the postinst script by customizing the
script based on build platform. This commit seeks to update prerm and postrm in
a similar manner, which reduces the amount of shell code and should fix problems
we encountered trying to remove/purge the package.
=> [package-scripts] templatize prerm, postrm

site-cookbooks/omnibus_sensu/recipes/default.rb
Closes #98 with some awesome hard-coded assumptions!
=> use awscli to upload artifacts on windows

config/software/openssl.rb
An attempt to fix https://github.com/sensu/sensu-omnibus/issues/124.
=> Force 32-bit OpenSSL on Windows

.kitchen.yml
AMI-specific fixes for errors introduced in #134
=> [test-kitchen] fix up ebs block device mappings

Rakefile
Should make sure that output streams successfully on e.g. Travis, at least as far as Rake is concerned
=> Make sure Rake keeps stdout synced

config/projects/sensu.rb, config/software/ruby.rb
=> Use Ruby 2.4.0 & Rubygems 2.6.10

config/software/sensu-gem.rb, config/templates/package-scripts/postrm.erb, config/templates/package-scripts/prerm.erb
A few fixes necessary to fix builds on Solaris 10.
=> Solaris 10 fixes

config/projects/sensu.rb, config/software/ruby.rb, config/software/rubygems.rb
=> Upgrade to Ruby 2.4.1

config/software/sensu-gem.rb
=> Use sensu-plugin 1.4.5 and 2.0.0

README.md, config/projects/sensu.rb
- Explicitly includes redhat-lsb on RedHat platforms
- Resolves sensu/sensu-docs#487
=> Explicitly include redhat-lsb package on RedHat-alikes

README.md, config/projects/sensu.rb, config/software/sensu-gem.rb
Bringing in fixes in RPM package dependencies
=> Merging in redhat-lsb changes from 0.28

Berksfile.lock, Gemfile
* update omnibus cookbook ref in berksfile to bring in freebsd fix https://github.com/sensu/omnibus-cookbook/pull/3
* update berkshelf version in gemfile to silence annoying warnings
=> Update omnibus cookbook and berkshelf gem versions

files/sensu-gem/bin/sensu-service
=> Update GEM_PATH in sensu-service binstub

config/templates/sensu-gem/sysvinit/sensu-service.erb
=> [sysvinit] add $daemon_exec indicating the executable we expect pid_pgrep to find

config/projects/sensu.rb, config/software/shebang-cleanup.rb
Should address e.g. sensu/sensu-puppet#636 at the omnibus level, as it should probably be!
=> importing shebang-cleanup from omnibus-software

config/templates/sensu-gem/sysvinit/sensu-service.erb
=> [sysvinit] when stopping, try pidfile first, fall back to pgrep

config/templates/package-scripts/postinst.erb
With detection and not a hard mapping!
=> Reload SystemD Units on Platforms Running SystemD

.travis.yml
=> Bump ruby to 2.4.1 & rubygems to 1.14.6 in travis

config/templates/package-scripts/postinst.erb
Fixes #228 
Please ignore indentation changes; they were automatically added as we're now using editorconfig in other projects.
The only additions are:
https://github.com/sensu/sensu-omnibus/blob/dff7808eb9d232c9202599a637a1a7294eae4576/config/templates/package-scripts/postinst.erb#L94-L95
and
https://github.com/sensu/sensu-omnibus/blob/dff7808eb9d232c9202599a637a1a7294eae4576/config/templates/package-scripts/postinst.erb#L125-L126
=> Use getent for user/group verification

.kitchen.yml, files/sensu-gem/bin/sensu-service
Also allow $ETC_DIR to be passed to the binstub. Fixes #225.
=> Allow overriding via service-specific defaults & sysconfig files

config/templates/package-scripts/prerm.erb
Fixes https://github.com/sensu/sensu-omnibus/issues/241
=> Return true if service stop fails on AIX

Berksfile, Berksfile.lock, site-cookbooks/omnibus_sensu/recipes/default.rb
update wix cookbook version, add dependency on mingw cookbook fork
=> Fix Windows build breakage around wix and msys2

config/templates/package-scripts/postrm.erb
we should really clean up properly after ourselfs
especially with systemd being a bit sensitive about its unit files, there is no need to have anything laying around there
=> clean up unit files when purged

Vagrantfile
This is to facilitate testing of omnibus changes before the go into CI without taking on EC2 expense.
=> Add Vagrantfile for testing

config/software/sensu-gem.rb
Signed-off-by: Sean Porter <portertech@gmail.com>
=> install sensu-translator 0.3.0, 0.2.0 could not load required deps

config/templates/package-scripts/postinst.erb, config/templates/package-scripts/posttrans.erb
Fixes #264 
I was able to reproduce the issue described in #264; the issue does not persist when upgrading to a package built with this PR.
=> Reload systemd  daemons in posttrans

config/projects/sensu.rb, config/software/ruby.rb
Fixes #250 
Fixes https://github.com/sensu/sensu/issues/1867
=> Ruby version bump to 2.4.4

config/templates/package-scripts/postinst.erb
Closes #274.
Verified working on Ubuntu & CentOS.
=> Fix user/group check on linux

config/software/eventmachine.rb
Signed-off-by: Sean Porter <portertech@gmail.com>
=> Bump eventmachine to 1.2.7, bug and build fixes

config/software/sensu-gem.rb
Closes https://github.com/sensu/sensu-omnibus/issues/286
Signed-off-by: Sean Porter <portertech@gmail.com>
=> Bump sensu-translator to 1.0.0 for Sensu Go GA

.kitchen.yml
=> use new subnet, old subnet was deleted
